language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rmaznytsia/docker-react -f Dockerfile.dev .  


script:
  - docker run -e CI=true rmaznytsia/docker-react npm run test